# Generated by Django 2.2.6 on 2019-10-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191009_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='hospitals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Hospital'),
            preserve_default=False,
        ),
    ]
