# Generated by Django 2.2.6 on 2019-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191009_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(to='main.Department'),
        ),
    ]
